services:
  db:
    image: postgres:15-alpine
    container_name: barberbot-db
    environment:
      - POSTGRES_DB=BarberBotDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Password123
    ports:
      - "5432:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: barberbot-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seqdata:/data

  api:
    build:
      context: .
      dockerfile: BarberBot.WebApi/Dockerfile
    container_name: barberbot-api
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=BarberBotDb;Username=postgres;Password=YourStrong@Password123
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5117:8080"
    depends_on:
      - db
      - seq

  web:
    build:
      context: ./BarberBot.Clients/BarberBot.WebApp
      dockerfile: Dockerfile
    container_name: barberbot-web
    ports:
      - "5173:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgvolume:
  seqdata:
